version: "3.9"

services:
  django:
    container_name: django
    image: django:custom
    build: ./django
    environment:
      - POSTGRES_HOST=database
    env_file:
      - .env
    ports:
      - ${BE_PORT}:${BE_PORT}
      - ${BE_PORT_ALT}:${BE_PORT_ALT}
    volumes:
      - ${HOST_SRC}:${DOCK_DST}
    networks:
      - bedb
    depends_on:
      database:
        condition: service_healthy
  
  database:
    container_name: database
    image: database:custom
    build: ./postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - bedb
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bedb:
    name: bedb

volumes:
  dev-db-data:
    name: dev-db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data