version: "3.9"

services:
  django:
    build: ./django
    env_file:
      - .env
    ports:
      - ${BE_PORT}:${BE_PORT}
      - ${BE_PORT_ALT}:${BE_PORT_ALT}
    volumes:
      - ${HOST_SRC}:${DOCK_DST}
    networks:
      - bedb

  # database:
  #   image: postgres
  #   environment:
  #     - name=value

networks:
  bedb: