name: Django CI with Makefile

on: 
  push:
    branches: 
      - main
      - git-workflows
  pull_request:
    branches: 
      - main
      - git-workflows

  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Create data folder
      run: make create_data_folder

    - name: Build containers
      run: make build

    - name: Bring up services
      run: make up

    - name: Run Django tests
      run: docker exec ${DJANGO_CONTNR} python manage.py test

    - name: Clean up
      run: make down
