name: Django CI

on:
  push:
    branches:
      - "main"
      - 'unittest'
  pull_request:
    branches:
      - "main"
      - 'unittest'

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      env:
        DOCKER_DRIVER: overlay2
      options: --cpus 1
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    steps:
      - name: Check for dockerenv file
        run: |
          if [ -f /.dockerenv ]; then
            echo "Found dockerenv"
          else
            echo "No dockerenv"
          fi
      - name: Build Docker Image
          run: docker build -t bookoverflow -f ../../src/django/Dockerfile .
      - name: Run Tests
        run: |
          docker run my_django_app python src/django/app/manage.py test
