name: Django CI

on:
  push:
    branches:
      - "main"
      - 'unittest'
  pull_request:
    branches:
      - "main"
      - 'unittest'

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      env:
        DOCKER_DRIVER: overlay2
      options: --cpus 1
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    working-directory: ${{ github.workspace }}/django-app
    steps:
      - name: Output Workflow File Location
        run: |
          echo "Workflow files are running in: $(pwd)"

      - name: Verify Documentation Folder Existence
        run: |
          if [ -d "Documentation" ]; then
            echo "Documentation folder exists."
          else
            echo "Documentation folder does not exist."
          fi

      - name: Build Docker Image
        run: docker build -t bookoverflow -f src/django/Dockerfile .
      
      - name: Run Tests
        run: |
          docker run my_django_app python src/django/app/manage.py test
